baseURL = ""
languageCode = "en-us"
title = "Securely using Cryptography with CogniCrypt"
theme = "hugo-solstice-theme"


[permalinks]
  news = "/:sections/:slug/"
  
[[menu.main]]
  name = "Downloads"
  weight = -150
  identifier = "downloads"
  url= "/downloads/"

[[menu.main]]
  name = "Documentation"
  weight = -100
  identifier = "documentation"
  url= "/documentation/"  
  
[[menu.main]]
  name = "Contributing"
  weight = -70
  identifier = "contributing"
  url= "/contributing/"  
  
[[menu.main]]
  name = "News"
  weight = -50
  identifier = "news"
  url= "/news/"
  
  

DefaultContentLanguage = "en"

metaDataFormat = "yaml"

#googleAnalytics = "UA-910670-30"

disableKinds = ["cloud", "devices", "events", "gateway", "hardware", "member", "news", "open-iot-challenge-entries", "resources"]

paginate  = 6
buildFuture = true

[Params]
    
description = "iot.eclipse.org is where you can learn about the technologies developed at Eclipse to make Internet of Things (IoT) development simpler. These technologies aim at establishing an open, end-to-end, IoT stack."
  subtitle = ""
  seo_title_suffix = " | CogniCrypt"
  keywords = [""]
#  logo = "assets/images/iot-logo.png"
  styles = "assets/css/bootstrap.css"
  js = "assets/js/main.js"

  favicon = "favicon.ico"
#  share_img = "site_preview.jpg"
#  gcse = "011805775785170369411:p3ec0igo0qq"
# header_wrapper_class = "header-default-bg-img"
# subtheme = "jakarta"
# call_for_action_text = ""
# call_for_action_url = ""
# call_for_action_icon = ""

[Author]
  name = "Eclipse Foundation"
  website = "https://www.eclipse.org"
  email = "webdev@eclipse-foundation.org"
#  facebook = "eclipseiot"
#  twitter = "CogniCrypt"
#  youtube = "EclipseFdn"
#  googleplus = "+Eclipse"
#  linkedin = "company/eclipse-foundation/"  