sudo: true
dist: trusty

install:
  - sudo apt-get --yes install autoconf libtool nasm
  - npm install
  - wget https://github.com/gohugoio/hugo/releases/download/v0.40.1/hugo_0.40.1_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  
script:
  - npm run production
  - hugo --source=exampleSite --baseUrl=https://eclipsefdn.github.io/hugo-solstice-theme/ --destination=../public
  - rm -rf public/fonts && rm -rf public/js && rm -rf public/css && rm -rf public/images

cache:
  directories:
    - "node_modules"

deploy:
  local-dir: public
  repo: EclipseFdn/hugo-solstice-theme
  target-branch: gh-pages
  provider: pages
  keep-history: false
  skip-cleanup: true
  github_token: $GITHUB_TOKEN
  email: chris.guindon@eclipse-foundation.org
  name: Christopher Guindon
  on:
    branch: master