name = "solstice"
license = "EPL-v2"
licenselink = "https://github.com/EclipseFdn/hugo-solstice-theme/blob/master/LICENSE.md"
description = ""
homepage = "https://www.eclipse.org/"
tags = ["", ""]
features = ["", ""]
min_version = 0.32

[author]
  name = "Christopher Guindon"
  homepage = "https://www.chrisguindon.com"

